menu:
- {name: 'about', url: '/about'}
- {name: 'publications', url: '/publications'}
#- {name: 'projects', url: '/courses'}
- {name: 'cv', url: '/assets/cv_rm_2025-3.pdf'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'about'}
- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

# courses:
#  - {name: 'Arabic Forced Aligner', url: 'ar_forced_aligner.md'}
#  - {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
#  - {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/rvmeyer'}
# - {icon: 'twitter', link: 'https://twitter.com/paululele'}
# - {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/lenpaul'}

contacts:
- {name: 'Rachel Meyer', title: 'PhD Candidate', department: 'Linguistics', institution: 'University of Florida', institution_address: 'Gainesville, Florida, USA', email: '<a href = "mailto:rvmeyer713@gmail.com>Email</a>', github: '<a href ="github.com/rvmeyer">Github</a>', linkedin: '<a href = "linkedin.com">LinkedIn', image: 'assets/beach_pic.png'}
